//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickSearch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickSearch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickSearch.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building search index....
        /// </summary>
        internal static string Building_search_index {
            get {
                return ResourceManager.GetString("Building_search_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were errors while building the search index.
        ///
        ///See below to view the locations which could not be added..
        /// </summary>
        internal static string ErrorsWhileBuildingTheSearchIndex {
            get {
                return ResourceManager.GetString("ErrorsWhileBuildingTheSearchIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ExitMenuText {
            get {
                return ResourceManager.GetString("ExitMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon2 {
            get {
                object obj = ResourceManager.GetObject("icon2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ookii_Dialogs {
            get {
                object obj = ResourceManager.GetObject("Ookii_Dialogs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options....
        /// </summary>
        internal static string OptionsMenuText {
            get {
                return ResourceManager.GetString("OptionsMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Ctrl+Enter to open file location..
        /// </summary>
        internal static string Press_Ctrl_Enter_to_open_file_location {
            get {
                return ResourceManager.GetString("Press_Ctrl_Enter_to_open_file_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press F1 for options..
        /// </summary>
        internal static string Press_F1_for_options {
            get {
                return ResourceManager.GetString("Press_F1_for_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickSearch is still running..
        /// </summary>
        internal static string QuickSearch_is_still_running {
            get {
                return ResourceManager.GetString("QuickSearch_is_still_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        internal static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a search by pressing &quot;{0}&quot;.
        ///To close, right click and choose &quot;Exit&quot;..
        /// </summary>
        internal static string SearchTipFormat {
            get {
                return ResourceManager.GetString("SearchTipFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To close, right click and choose &quot;Exit&quot;..
        /// </summary>
        internal static string To_close_right_click_and_choose_Exit {
            get {
                return ResourceManager.GetString("To_close_right_click_and_choose_Exit", resourceCulture);
            }
        }
    }
}
